"use client";

import Link from "next/link";
import { Heart, LogOut, MapPin, Package, ShoppingBag, UserRound } from "lucide-react";
import SiteHeader from "@/components/layout/SiteHeader";
import { useStore } from "@/components/providers/StoreProvider";

export default function CustomerAccount() {
  const { userName, userRole, favoriteIds, openAuth, openWishlist, signOut } = useStore();

  if (!userName || userRole !== "shopper") {
    return <main className="min-h-screen p-0 sm:p-5 lg:p-8"><div className="mx-auto min-h-screen max-w-[1440px] overflow-hidden bg-white shadow-[0_28px_90px_rgba(107,44,62,.16)] sm:rounded-[28px]"><SiteHeader /><section className="grid min-h-[70vh] place-items-center p-6"><div className="max-w-lg text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#fff0f4] text-[#e34370]"><UserRound size={30} /></span><h1 className="mt-5 text-4xl font-black tracking-[-.04em]">Your BelGlow account</h1><p className="mt-3 text-[#75696e]">Sign in as a shopper to view orders, saved products, and account details.</p><button onClick={openAuth} className="mt-7 rounded-full bg-[#ef4b74] px-7 py-3.5 font-bold text-white">Sign in to your account</button></div></section></div></main>;
  }

  return <main className="min-h-screen p-0 sm:p-5 lg:p-8"><div className="mx-auto min-h-screen max-w-[1440px] overflow-hidden bg-[#fffdfd] shadow-[0_28px_90px_rgba(107,44,62,.16)] sm:rounded-[28px]"><SiteHeader /><section className="bg-[linear-gradient(115deg,#fff7f9,#f8d8e1)] px-5 py-10 sm:px-10 lg:px-16"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#df3e69]">Shopper account</p><div className="mt-2 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-black tracking-[-.05em] sm:text-5xl">Welcome, {userName}</h1><p className="mt-2 text-[#695d62]">Everything you love from BelGlow, all in one place.</p></div><button onClick={signOut} className="inline-flex items-center justify-center gap-2 rounded-full border border-[#dcaeba] bg-white px-5 py-3 text-sm font-bold text-[#c13e64]"><LogOut size={17} /> Sign out</button></div></section><section className="grid gap-5 px-5 py-8 sm:px-10 lg:grid-cols-[.75fr_1.25fr] lg:px-16 lg:py-12"><aside className="space-y-4"><AccountCard icon={<UserRound />} title="Profile"><p className="text-sm text-[#75696e]">{userName}<br />shopper@belglow.demo</p><button className="mt-4 text-sm font-bold text-[#df3e69]">Edit profile</button></AccountCard><AccountCard icon={<MapPin />} title="Delivery address"><p className="text-sm text-[#75696e]">Add a Belize delivery address for faster checkout.</p><button className="mt-4 text-sm font-bold text-[#df3e69]">Add address</button></AccountCard></aside><div className="space-y-5"><AccountCard icon={<Package />} title="Recent orders"><div className="mt-4 rounded-2xl border border-[#eee1e5] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Order #BG12084</p><p className="mt-1 text-xs text-[#817579]">September 24, 2026 · 2 items</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Delivered</span></div><div className="mt-4 flex items-center justify-between border-t border-[#eee1e5] pt-4"><strong>BZ$52.00</strong><button className="text-sm font-bold text-[#df3e69]">View order</button></div></div><Link href="/shop" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#df3e69]"><ShoppingBag size={17} /> Continue shopping</Link></AccountCard><AccountCard icon={<Heart />} title="Saved products"><p className="text-sm text-[#75696e]">You have {favoriteIds.length} {favoriteIds.length === 1 ? "product" : "products"} saved to your wishlist.</p><button onClick={openWishlist} className="mt-4 rounded-full bg-[#ef4b74] px-5 py-2.5 text-sm font-bold text-white">Open saved products</button></AccountCard></div></section></div></main>;
}

function AccountCard({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-[#eee1e5] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#fff0f4] text-[#df3e69]">{icon}</span><h2 className="text-lg font-black">{title}</h2></div><div className="mt-4">{children}</div></section>; }
