"use client";

import Link from "next/link";
import { useStore } from "@/components/providers/StoreProvider";

type ShippingMethod = { code: string; name: string; description: string | null; price_cents: number };

export default function GuestCheckout({ shippingMethods }: { shippingMethods: ShippingMethod[] }) {
  const { cart, products } = useStore();
  const lines = cart.map((id) => products.find((product) => product.id === id)).filter((product) => product !== undefined);
  const subtotal = lines.reduce((sum, product) => sum + Math.round(product.price * 100), 0);

  return <>
    <p className="mt-3 text-sm leading-6 text-[#75696e]">You can shop and check out as a guest—no shopper account is required. Your seller or admin account is only needed for marketplace tools.</p>
    {!lines.length ? <section className="mt-7 rounded-2xl bg-[#fff5f7] p-5 text-sm text-[#75696e]">Your bag is empty.<Link href="/shop" className="ml-2 font-bold text-[#df3765] underline">Browse products</Link></section> : <>
      <section className="mt-7 rounded-2xl border border-[#f0e2e6] p-5"><h2 className="font-bold">Your bag ({lines.length} {lines.length === 1 ? "item" : "items"})</h2><div className="mt-3 divide-y divide-[#f0e2e6]">{lines.map((product, index) => <div key={`${product.id}-${index}`} className="flex justify-between gap-4 py-3"><div><p className="font-semibold">{product.name}</p><p className="text-xs text-[#817679]">{product.category}</p></div><strong className="shrink-0">BZ${product.price.toFixed(2)}</strong></div>)}</div><p className="mt-3 flex justify-between border-t border-[#f0e2e6] pt-4 font-bold"><span>Subtotal</span><span>BZ${(subtotal / 100).toFixed(2)}</span></p></section>
      <section className="mt-5 rounded-2xl border border-[#f0e2e6] p-5"><h2 className="font-bold">Guest details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Email<input type="email" autoComplete="email" placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label><label className="text-sm font-semibold">Phone<input type="tel" autoComplete="tel" placeholder="+501" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label><label className="text-sm font-semibold sm:col-span-2">Recipient name<input autoComplete="name" placeholder="Name for delivery" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label><label className="text-sm font-semibold sm:col-span-2">Street address<input autoComplete="street-address" placeholder="Street address" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label><label className="text-sm font-semibold">City or town<input autoComplete="address-level2" placeholder="Belize City" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label><label className="text-sm font-semibold">District<input autoComplete="address-level1" placeholder="District" className="mt-2 h-12 w-full rounded-xl border border-[#e7dade] px-4 font-normal" /></label></div></section>
      <section className="mt-5 rounded-2xl border border-[#f0e2e6] p-5"><h2 className="font-bold">Delivery options</h2>{shippingMethods.length ? <div className="mt-3 space-y-3">{shippingMethods.map((method, index) => <label key={method.code} className="flex cursor-pointer items-start justify-between gap-4 rounded-xl bg-[#fff8fa] p-4"><span className="flex gap-3"><input type="radio" name="shipping" value={method.code} defaultChecked={index === 0} className="mt-1 accent-[#ef4b74]" /><span><span className="block font-semibold">{method.name}</span><span className="mt-1 block text-xs text-[#817679]">{method.description}</span></span></span><strong className="shrink-0">BZ${(method.price_cents / 100).toFixed(2)}</strong></label>)}</div> : <p className="mt-3 text-sm text-[#75696e]">Delivery options are not configured yet.</p>}</section>
      <section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900" role="status"><h2 className="font-bold">Payment setup still required</h2><p className="mt-2">Guest shopping is enabled; however, BelGlow cannot safely place or charge an order until a payment processor that supports Belize and marketplace payouts is selected and integrated. No order or charge is created on this page.</p><p className="mt-2">Please don’t collect or send card details by email or chat.</p><button type="button" disabled className="mt-4 w-full cursor-not-allowed rounded-full bg-[#ef4b74] py-3.5 font-bold text-white opacity-50">Payments coming soon</button></section>
    </>}
  </>;
}
